apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft-bedrock-server-idv
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: public-cd-apps
  source:
    path: kgtkr/minecraft-bedrock-server-idv
    repoURL: https://github.com/kgtkr/public-cd
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: minecraft-bedrock-server-idv
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
