apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-bedrock-server-idv-minecraft-bedrock
  namespace: minecraft-bedrock-server-idv
spec:
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: minecraft-bedrock-server-idv-minecraft-bedrock
    spec:
      containers:
        - image: rclone/rclone:1.65
          name: rclone
          resources:
            requests:
              cpu: "10m"
              memory: "300Mi"
          command:
            - /bin/sh
            - -c
            - |
              while true; do
                rclone -v sync /data/worlds minio:/worlds --fast-list
                sleep 1h
              done
          volumeMounts:
            - mountPath: /config/rclone
              name: minio-secret
              readOnly: true
            - mountPath: /data
              name: datadir
              readOnly: true
      volumes:
        - name: minio-secret
          secret:
            secretName: minio-secret
