apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-bedrock-server-idv-minecraft-bedrock
spec:
  template:
    spec:
      containers:
        - name: unmined
          image: ghcr.io/kgtkr/unmined-docker:20240229210113704-faaa3c8
          command:
            - "sh"
            - "-c"
            - |
              sleep infinity
          volumeMounts:
            - mountPath: /data
              name: datadir
              readOnly: true
            - mountPath: /unmined-out
              name: unmined-out
      volumes:
        - name: unmined-out
          emptyDir: {}
