apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-bedrock-server-idv-minecraft-bedrock
spec:
  template:
    spec:
      containers:
        - name: unmined
          image: ghcr.io/kgtkr/unmined-docker:20240229210113704-faaa3c8
          command:
            - "sh"
            - "-c"
            - |
              while true; do
                ./unmined-cli web render --world=/data/worlds/level --output=/unmined-out
                mv /unmined-out/unmined.index.html /unmined-out/index.html
                sleep 60h
              done
          volumeMounts:
            - mountPath: /data
              name: datadir
              readOnly: true
            - mountPath: /unmined-out
              name: unmined-out
        - name: unmined-web
          image: ghcr.io/static-web-server/static-web-server:2
          ports:
            - containerPort: 8080
              name: unmined-web
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: SERVER_ROOT
              value: "/public"
          volumeMounts:
            - mountPath: /public
              name: unmined-out
              readOnly: true
      volumes:
        - name: unmined-out
          emptyDir: {}
