apiVersion: v1
kind: Service
metadata:
  name: unmined-nginx
spec:
  ports:
    - port: 80
      targetPort: unmined-nginx
  selector:
    app: minecraft-bedrock-server-idv-minecraft-bedrock
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unmined-nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    cert-manager.io/cluster-issuer: letsencrypt-issuer
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - mc-idv-unmined.kgtkr.net
      secretName: ingress-cert
  rules:
    - host: mc-idv-unmined.kgtkr.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: unmined-nginx
                port:
                  number: 80
