apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unmined-web
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    cert-manager.io/cluster-issuer: letsencrypt-issuer
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - mc-idv-unmined.kgtkr.net
      secretName: unmined-web-ingress-cert
  rules:
    - host: mc-idv-unmined.kgtkr.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: unmined-web
                port:
                  name: http
---
apiVersion: v1
kind: Service
metadata:
  name: unmined-web
spec:
  ports:
    - port: 80
      name: http
  selector:
    app.kubernetes.io/name: unmined-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unmined-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: unmined-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: unmined-web
      annotations:
        kubectl.kubernetes.io/default-container: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.27.4
          resources:
            requests:
              cpu: "10m"
              memory: "300Mi"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
              readOnly: true
        - name: rclone
          image: rclone/rclone:1.65
          resources:
            requests:
              cpu: "10m"
              memory: "300Mi"
          command:
            - /bin/sh
            - -c
            - |
              while true; do
                rclone -v sync minio:/unmined /data/html --fast-list
                cp /data/unmined-web-indexhtml/unmined-web-index.html /data/html/index.html
                sleep 1h
              done
          volumeMounts:
            - mountPath: /data/html
              name: html
            - mountPath: /config/rclone
              name: minio-secret
              readOnly: true
            - mountPath: /data/unmined-web-indexhtml
              name: unmined-web-indexhtml
              readOnly: true
      volumes:
        - name: html
          emptyDir: {}
        - name: unmined-web-indexhtml
          configMap:
            name: unmined-web-indexhtml
        - name: minio-secret
          secret:
            secretName: minio-secret
