apiVersion: v1
kind: Service
metadata:
  name: mc-router-bedrock
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
    metallb.universe.tf/address-pool: public-ips
    external-dns.alpha.kubernetes.io/hostname: mc-idv.kgtkr.net,minecraft-bedrock.kgtkr.net
